### ISSUE TITLE
Access in Router

### ISSUE THREAD

**Issue by harkus** [liamrota/vue3-snotify#1]
I've tried many ways to access this.$snotify in Vue 3 router beforeEach.

If you can provide a how-to or find a way to enable this feature, that would be amazing. :)

**Comment by liamrota** [comment]
After you mount the app you could do window.$snotify = app.config.globalProperties.$snotify; 
Then call $snotify in your router. (without 'this')

**Comment by harkus** [comment]
Hi liamrota, thanks for responding.

That worked brilliantly. I needed to add the eslint line 
`// eslint-disable-next-line no-undef`
Above the line to avoid the error, but it worked.

Thank you!

I can't find any other toast plugins that allow notifications and confirmations for consistency.

**Comment by liamrota** [comment]
great, you're welcome
