### ISSUE TITLE
Missing async function

### ISSUE THREAD

**Issue by chiribuc** [liamrota/vue3-snotify#3]
Hi there,

I've been migrating from `vue-snotify` to `vue3-snotify` in my VueJS project and encountered an issue regarding the absence of the expected async function.

Here's a snippet of how the async function was used in the old version:

```js
this.$snotify.async(`Link checking PR #${id}...`, () => new Promise((resolve, reject) => {
  DistributionsRepository.linkCheck(id)
    .then(() => {
      resolve({
        body: 'PR link checked!',
        config: {
          timeout: 2000,
          closeOnClick: true
        }
      });
      this.retrieveReportCounters();
    })
    .catch(() => {
      this.loading = false;
      reject({
        body: 'Error occurred during PR link check!',
        config: {
          timeout: 2000,
          closeOnClick: true
        }
      });
    });
}));

```

However, when attempting to use this functionality, I encountered the following error:

```
Uncaught TypeError: this.$snotify.async is not a function
```

It seems that the async function is missing or not implemented as expected in the current version of the vue3-snotify package.

Could you please provide guidance on this matter or consider addressing it in a future release?
Your assistance in resolving this issue would be greatly appreciated.

Thank you for your time and effort in maintaining this valuable npm package.

Best regards,
Robert

**Comment by palmer-rm** [comment]
Hi @chiribuc, sorry for the late response.

The `async` function was added in [this PR](https://github.com/rotamaster/vue3-snotify/pull/14), and has gone into the `0.1.0` release.
